// This is our products database for now. Later we will replace this with database and redux state
export const globoProducts = [
  {
    productId: '08a08a53-f3a0-42cf-95ff-f3220d82a09d',
    label: 'Test',
    title: 'Test',
    description: 'Test',
    image: 'https://reactnative.dev/img/tiny_logo.png',
  },
  {
    productId: '0b56fd57-adfb-4adb-8c76-51a3dda4d4eb',
    label: 'Test',
    title: 'Test',
    description: 'Test',
    image: 'https://reactnative.dev/img/tiny_logo.png',
  },
  {
    productId: '017a33dc-65b1-4309-9d34-25e35276a295',
    label: 'Test',
    title: 'Test',
    description: 'Test',
    image: 'https://reactnative.dev/img/tiny_logo.png',
  },
  {
    productId: '44e0bde9-fac3-4af7-99bf-ed170dc908d4',
    label: 'Test',
    title: 'Test',
    description: 'Test',
    image: 'https://reactnative.dev/img/tiny_logo.png',
  },
  {
    productId: 'bb96fe2a-247f-41af-b4b0-0de4340996fa',
    label: 'Test',
    title: 'Test',
    description: 'Test',
    image: 'https://reactnative.dev/img/tiny_logo.png',
  },
  {
    productId: 'f8c565fc-5e8c-4ea0-b30b-d31fa6bd6b85',
    label: 'Test',
    title: 'Test',
    description: 'Test',
    image: 'https://reactnative.dev/img/tiny_logo.png',
  },
  {
    productId: '26f1b24f-2877-4124-b8bc-1693f18d56fa',
    label: 'Test',
    title: 'Test',
    description: 'Test',
    image: 'https://reactnative.dev/img/tiny_logo.png',
  },
  {
    productId: 'f2127011-6cc9-49a4-baaf-9250b950564e',
    label: 'Test',
    title: 'Test',
    description: 'Test',
    image: 'https://reactnative.dev/img/tiny_logo.png',
  },
  {
    productId: 'dfdd9714-0a15-46d9-a12a-fa228bbba984',
    label: 'Test',
    title: 'Test',
    description: 'Test',
    image: 'https://reactnative.dev/img/tiny_logo.png',
  },
  {
    productId: '8c21b83f-e9a3-46af-8f62-122f967737ca',
    label: 'Test',
    title: 'Test',
    description: 'Test',
    image: 'https://reactnative.dev/img/tiny_logo.png',
  },
];
